import { Link, useNavigate } from "react-router-dom";
import useSecureAuthDownLine from "../../hooks/useSecureAuthDownLine";
import useQRCODE from "../../hooks/useQRCODE";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { config } from "../../utils/config";
import axios from "axios";
import Error from "../../components/Notification/Error";
import Success from "../../components/Notification/Success";

const SecureAuth = () => {
  const token = localStorage.getItem("adminToken");
  const qrValidate = config?.result?.endpoint?.qrValidate;
  const { handleSubmit, register } = useForm();
  const { secretSecureAuth } = useSecureAuthDownLine();
  const { qrCodeAndKey, refetchQrCodeAndKey } = useQRCODE(
    secretSecureAuth?.secret
  );

  const [successLogin, setSuccessLogin] = useState("");
  const [errLogin, setErrLogin] = useState("");
  const navigate = useNavigate();

  useEffect(() => {
    refetchQrCodeAndKey();
  }, [refetchQrCodeAndKey, secretSecureAuth?.secret]);

  const handleLoginByQrCode = async ({ code }) => {
    const res = await axios.post(
      qrValidate,
      {
        code,
        secret: qrCodeAndKey?.secret,
        type: secretSecureAuth?.success ? "deactivate" : "activate",
      },
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );
    const result = res.data;
    if (result?.success) {
      setSuccessLogin(result?.message);
      setTimeout(() => {
        localStorage.clear();
        navigate("/login");
      }, 2000);
    } else {
      setErrLogin(result?.message);
    }
  };

  return (
    <div data-v-b00d14ae="" className="page-content">
      {errLogin && <Error message={errLogin} setMessage={setErrLogin} />}
      {successLogin && (
        <Success message={successLogin} setMessage={setSuccessLogin} />
      )}
      <div data-v-b00d14ae="">
        <div data-v-b00d14ae="" className="security-auth">
          <div className="row">
            <div className="col-12">
              <div className="page-title-box d-flex align-items-center justify-content-between">
                <h4 className="mb-0 font-size-18">Secure Auth Verification</h4>
                <div className="page-title-right">
                  <ol className="breadcrumb m-0">
                    <li className="breadcrumb-item">
                      <Link to="/" className="" target="_self">
                        Home
                      </Link>
                    </li>
                    <li className="breadcrumb-item active">
                      <span aria-current="location">Secure Auth</span>
                    </li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
          <div>
            <div className="card-body">
              <div className="text-center">
                <b>Secure Auth Verification Status:</b>
                <span
                  className={`badge badge-danger ${
                    secretSecureAuth?.success ? "badge-light" : "badge-danger"
                  }`}
                >
                  {secretSecureAuth?.success ? "Enabled" : "Disabled"}
                </span>
              </div>
              <div className="mt-2 text-center">
                Please select below option to enable secure auth verification
              </div>
              <div className="casino-report-tabs mt-3">
                <ul className="nav nav-tabs">
                  <li className="nav-item pointer">
                    <a className="nav-link active">
                      Enable Using Google Authenticator
                    </a>
                  </li>
                </ul>
              </div>
              <div className="tab-content mt-4">
                <div className="tab-pane mobile-app active">
                  <div className="text-center">
                    <div id="container">
                      <h1 style={{ fontSize: "2.03125rem", fontWeight: "500" }}>
                        2-Step Verification using Google Authenticator
                      </h1>
                      <div id="device">
                        <p>
                          Enter the verification code generated by Google
                          Authenticator app on your phone.
                        </p>
                        <div id="img">
                          <img src={qrCodeAndKey?.qrCodeUrl} alt="" />
                        </div>

                        <form onSubmit={handleSubmit(handleLoginByQrCode)}>
                          <br />
                          <br />
                          <label style={{ marginRight: "7px" }}>
                            Enter Google Authenticator Code{" "}
                          </label>
                          <input
                            {...register("code")}
                            type="number"
                            name="code"
                          />
                          <input type="submit" className="button" />
                        </form>
                      </div>
                      <div style={{ textAlign: "center" }}>
                        <h3
                          style={{ fontSize: "1.421875rem", fontWeight: "500" }}
                        >
                          Get Google Authenticator on your phone
                        </h3>
                        <a href="https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8">
                          <img
                            className="app"
                            src="/apple.jpeg"
                            style={{ width: "150px" }}
                          />
                        </a>

                        <a
                          href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en"
                          style={{ marginLeft: "3px" }}
                        >
                          <img
                            className="app"
                            src="/google.jpeg"
                            style={{ width: "150px" }}
                          />
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SecureAuth;
