export const API = {
  changePassword: "",


  liveCasinoIframe: "",
  accessToken: "",
  notification: "",
  buttonValue: "",
  login: "",
  myMarket: "",
  searchEvent: "",
  order: "",
  whatsapp: "",
  checkUsername: "",
  register: "",
  otp: "",
  menu: "",
  balance: "",
  latestEvents: "",
  accountStatement: "",
  settledBets: "",
  activityLogs: "",
  ipDetails: "",
  group: "",
  currentBets: "",
  depositIframe: "",
  fantasyGames: "",
  ladder: "",
  auraCasino: "",
  diamondCasino: "",
  testCasino: "",
  liveCasinoWolf: "",
  exposure: "",
  odds: "",
  virtualCasino: "",
  slotsWolf: "",
  withdrawIframe: "",
  assets: "",
  downLineEdit:"",
  downLineEditForm:"",
  qrValidate:"",
  downline:"",
  adminExposure:"",
  qrCode:"",
  searchUser:"",
  Bank:"",
  createDownLine:"",
  marketAnalysis:"",
  partyWinLoss:"",
  userAuthentication:"",
  userHistory:"",

};

export const settings = {
  casino: "",
  siteTitle: "",
  forceLogin: "",
  registration: "",
  demoLogin: "",
  withdraw: "",
  deposit: "",
  siteUrl: "",
  balanceApiLoop: "",
  disabledDevtool: "",
  casinoCurrency: "",
  interval: "",
  URL:""
};
